version: '3'
services:
  app:
    image: openjdk:17-alpine
    ports:
      - 8080:8080
    volumes:
      - ../target/com.pinapp.challenge.ar-0.0.1-SNAPSHOT.jar:/app.jar
    command: java -jar app.jar

